name: Build and test

on:
  pull_request:

jobs:
  docker:
    name: Docker tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
